  // config ID (omit: created automatically)
  id: string
junjones 
  name: string
  // short description, displayed when choosing a config
  description: string
  // long description, displayed in the config details (optional, default = $description)
  long_description: string
  // org for which the config is available
  org: string
  // group for which the config is available (optional, default = '')
  group: string
  // indicates if the config is available for regular users (optional, default = true)
  user_trigger: boolean

  /* INPUTS */

  // accepted inputs
  inputs: Input[]
  // for each input slug, there may or may not be a corresponding input config (optional)
  input_configs: InputConfigMap
  // slug of the input considered as starting point (optional: can be empty)
  starting_point: string

  /* EXECUTION */

  // steps to execute
  steps: Step[]
  // locale (optional, default = 'fr')
  locale: 'en' | 'fr'# This workflow will trigger Datadog Synthetic tests within your Datadog organisation
# For more information on running Synthetic tests within your GitHub workflows see: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# To get started:

# 1. Add your Datadog API (DD_API_KEY) and Application Key (DD_APP_KEY) as secrets to your GitHub repository. For more information, see: https://docs.datadoghq.com/account_management/api-app-keys/.
# 2. Start using the action within your workflow

name: Run Datadog Synthetic tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Run Synthetic tests within your GitHub workflow.
    # For additional configuration options visit the action within the marketplace: https://github.com/marketplace/actions/datadog-synthetics-ci
    - name: Run Datadog Synthetic tests
      uses: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb # v1.4.0
      with:
        api_key: ${{secrets.DD_API_KEY}}
        app_key: ${{secrets.DD_APP_KEY}}
        test_search_query: 'tag:e2e-tests' #Modify this tag to suit your tagging strategy


